// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"44309f5469fdc054ed70863e7cc895be06840fc12db039f4a0be55cb0b38c13e8afddc1f831682846f308ee2695db8d3cd1e4f0867fad141ab2fc4f4c68d5274"}}
];
